# Generated by Django 5.2.7 on 2026-04-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portfolio_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Warehousing', 'Warehousing'), ('Residential', 'Residential'), ('S&F', 'S&F')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('inspection_date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('login_location_text', models.CharField(blank=True, max_length=255)),
                ('submit_location_text', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.site')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('control_item', models.TextField()),
                ('module', models.CharField(max_length=255)),
                ('item_status', models.CharField(choices=[('Done', 'Done'), ('Issue', 'Issue'), ('N/A', 'N/A')], max_length=10)),
                ('manual_value', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('evidence_image', models.ImageField(upload_to='checklist_evidence/')),
                ('escalation_level', models.CharField(blank=True, max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.checklistsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('site_supervisor', 'Site Supervisor'), ('asset_manager', 'Asset Manager'), ('portfolio_head', 'Portfolio Head'), ('admin', 'Admin')], default='site_supervisor', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
